version: "3.9"
services:
  ansible:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ansible_controller_client
    volumes:
    - type: bind
      source: ./ansible_files
      target: /home/ansible_controller_client/ansible_files

  target1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ansible_target