name: Bootcamp workflow

on: push 

jobs: 
    job1:
        name: First job
        runs-on: ubuntu-latest
        steps:
        - name: Step One
          uses: actions/checkout@v2
        - name: Step two
          run: env | sort 
    job2:
        name: Second Job
        runs-on: windows-latest
        steps:
        - name: Step One
          uses: actions/checkout@v2
        - name: Step Two
          run: date
    job3:
        needs: [job1] 
        runs-on: macos-latest
        steps:
          - name: Step 1
            uses: actions/checkout@v2
          - name: Step 2
            run: |
              date
              touch ${{ secrets.MY_FILE_NAME }}.yml
              echo "My first file" >> ${{ secrets.MY_FILE_NAME }}.yml
              cat ${{ secrets.MY_FILE_NAME }}.yml
                pwd
          - name: Upload a Build Artifact
            uses: actions/upload-artifact@v2.3.1
            with:
              name: my_custom_file
              path: ./${{ secrets.MY_FILE_NAME }}.yaml
